name: Automated Commit

on:
  push:
    branches: [main]  # sửa lại nếu bạn dùng main thay vì master
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Update Timestamp File
        run: |
          current_time=$(date '+%Y-%m-%d %H:%M:%S')
          echo "Updated on $current_time" > TIMESTAMP.txt

      - name: Setup Git Configuration
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Prepare Commit
        run: |
          current_time=$(date '+%Y-%m-%d %H:%M:%S')
          commit_messages=("Update: ⏰" "Refresh: 🔄" "Renew: 🌟" "Revise: 📝" "Amend: 🛠" "Adjust: 🔧" "Change: 📈" "Modify: 🖊" "Transform: 🌀" "Revamp: 🌈")
          random_msg=${commit_messages[$RANDOM % ${#commit_messages[@]}]}
          git add TIMESTAMP.txt
          git commit -m "$random_msg - $current_time" || echo "No changes to commit."

      - name: GitHub Push
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
